- 👋 Hi, I’m @Liefernando1
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Liefernando1/Liefernando1 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->

!steward !unlock Liefernando1 r=Because I'll be back contributing to Wikipedia as long as I don't cross wiki abuse and abuse multiple accounts.
